platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# use_modular_headers!
use_frameworks! :linkage => :static

target 'Focus Dating' do


  # # Pods for Focus
  # pod 'Firebase/Core', '~> 6.13.0'

  # # add the Firebase pod for Google Analytics
  # pod 'Firebase/Analytics'  
  # pod 'Firebase/Messaging'
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  # pod 'Firebase/Analytics', '10.10.0'
  # pod 'BoringSSL-GRPC', '0.0.24', :modular_headers => false
  # # pod 'gRPC-Core', '= 1.21.0', :modular_headers => false
  # pod 'gRPC-Core', '1.50.1', :modular_headers => false

  # pod 'BoringSSL-GRPC', '0.0.24'
  # pod 'gRPC-Core', '1.44.0'
  # pod 'BoringSSL-GRPC', '= 0.0.3', :modular_headers => false
  # pod 'gRPC-Core', '= 1.44.0', :modular_headers => false


  pod 'Firebase/Core', '~> 8.15.0'
  pod 'Firebase/Firestore', '~> 8.15.0'
  pod 'gRPC-Core', '= 1.44.0', :modular_headers => false
  pod 'BoringSSL-GRPC', '~> 0.0.24', :modular_headers => false


  pod 'nanopb', '~> 2.30908.0'

  pod 'Firebase/DynamicLinks', '8.15.0'
  pod 'Firebase/Analytics', '8.15.0'
  pod 'Firebase/Messaging', '8.15.0'
  pod 'GoogleAppMeasurement', '8.15.0'

 # Point to the installed version
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker/RNDateTimePicker.podspec'

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  
  pod 'FirebaseCore', '8.15.0'

  # pod 'FirebaseCoreExtension', :modular_headers => true
  # pod 'FirebaseAppCheckInterop', :modular_headers => true
  # pod 'FirebaseAuthInterop', :modular_headers => true
  # pod 'FirebaseMessagingInterop', :modular_headers => true
  # pod 'GTMSessionFetcher', :modular_headers => true

  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  # pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  # pod 'React-callinvoker', :path => '../node_modules/react-native/ReactCommon/jscallinvoker'

  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit'
  # pod 'FBSDKShareKit'

  # pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'


  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  # pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'
  

  

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  
  # pod 'appcenter', path: '../node_modules/appcenter/ios'
  # pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'
  # pod 'appcenter-crashes', path: '../node_modules/appcenter-crashes/ios'




  use_native_modules!
end

target 'Focus-tvOS' do
  # Pods for Focus-tvOS

  target 'Focus-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm", "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm", "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm", "RCTBridgeModuleNameForClass(strongModule))", "RCTBridgeModuleNameForClass(Class(strongModule)))")

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end


post_install do |installer|

    
      installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end

      

      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"

        end
       end

      # installer.aggregate_targets.each do |aggregate_target|
      #   aggregate_target.user_project.native_targets.each do |target|
      #     target.build_configurations.each do |config|
      #       config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
      #     end
      #   end
      #   aggregate_target.user_project.save
      # end
    
    
 ## Fix for XCode 12.5
    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
        "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
        find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
        "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")


    find_and_replace("../node_modules/react-native/Libraries/Image/RCTUIImageViewAnimated.m",
    "_currentFrame.CGImage;","_currentFrame.CGImage ;} else { [super displayLayer:layer];")

      #Fix after updating to Xcode 13.1
      find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
    find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
    "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
end

    


def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end



def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end